### ISSUE TITLE
上传反馈

### ISSUE THREAD

**Issue by zhugw** [prclin/interview#3]
1. 上传报错

```
java.lang.RuntimeException: 文件格式异常
	at com.bxtdata.interview.interview.service.impl.FileServiceImpl.saveBase64Image(FileServiceImpl.java:70)
```

suffix固定 上传可以成功
```
String suffix = "png"; //文件类型
```

<img width="1780" alt="image" src="https://github.com/prclin/interview/assets/4953871/7704fbd4-9ef8-4f75-b788-6835476a37dc">

按照你的设计来的话  上传成功了 可以从redis中删除这个id

**Comment by prclin** [comment]
已解决 #2
